### ISSUE TITLE
Missing geometry

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#19] opened 2018-08-13 10:44 UTC
1 and the same family with different values for IfcExportAs.
R2019, current-Github-exporter-version:

For IFC2x3CV2 & IFC4RV1: IfcExportAs=IfcBuildingElement**Proxy**(Type): cubes and geometry of modeltext are exported: OK! [correction: not IfcBuildingElement, but IfcBuildingElementProxy)

For IFC2x3CV2 & IFC4RV1: IfcExportAs=IfcChimney(Type)/IfcShadingDevice(Type)/IfcRampFlight(Type)/IfcStairFlight(Type): cubes are not exported.
For IFC4RV1: IfcExportAs=IfcCovering(Type)/IfcFooting(Type)/IfcPile(Type)/IfcRamp(Type)/IfcRoof(Type)/IfcSlab(Type)/IfcStair(Type)/IfcWall(Type): geometry of modeltext is not exported.

Sample file is attached.

<img width="834" alt="2018-08-13" src="https://user-images.githubusercontent.com/41319048/44027302-44c7e58e-9ef6-11e8-8d5f-6ee5d3ed9abd.png">

[2018-08-13 RVT IFC.zip](https://github.com/Autodesk/revit-ifc/files/2282645/2018-08-13.RVT.IFC.zip)

**Comment by AngelVelezSosa** [comment] 2018-08-13 14:06
Thanks for your testing - we will attempt to reproduce this.  Note that the "master" version in Git is definitely beta code - stable releases are on the App Store.  We'll likely be marking stable releases here too, in some way, for people downloading and building the code in their own.

**Comment by WawanSolihin** [comment] 2018-08-25 15:39
There seem to be 2 issues:
1. The missing cuboids (IfcChimneyType, etc.) seems to be simply that the parameters: IsValid_RevitEntityClass and IsValid_RevitEntityTypeClass are not ticked. Once these are ticked, the cuboids appear!
![image](https://user-images.githubusercontent.com/31854582/44619959-c01ac580-a8bf-11e8-8a83-37ed32bd2aa7.png)

2. There is minor issue that in some cases the text is missing because the geometry is Solid but the volume is 0. This has been fixed now. This how it looks in IFC2x3: 
![image](https://user-images.githubusercontent.com/31854582/44619971-f2c4be00-a8bf-11e8-9d80-98d592360eb9.png)
And in IFC4RV:
![image](https://user-images.githubusercontent.com/31854582/44619989-11c35000-a8c0-11e8-9dab-7f73883e00c2.png)

**Comment by dvrvb** [comment] 2018-08-25 16:49
Hi WawanSolihin,

I can confirm both issues:
1. Indeed, for 4 EntityClasses (Chimney -> StairFlight) the parameters were not ticked (so after all, they were not an issue)
2. I checked for IFC4RV, and the geometry of the other EntityClasses (Covering -> Wall) are now also exported!
Nice!
(issue closed)

Regards,
Dirk 

I have to rework now the testfile, since those parameters like "IsValid_RevitEntityClass" are not making any sense anymore.

**Comment by AngelVelezSosa** [comment] 2018-09-19 13:47
Closing this for now.  Reopen if the next version doesn't contain the fix.

**Closed by AngelVelezSosa** 2018-09-19 13:47 UTC
