### ISSUE TITLE
Some IFC components does not rotate

### ISSUE THREAD

**Issue by ERBRZ** [Autodesk/revit-ifc#565] opened 2022-12-12 13:14 UTC
Hi,

I just found that the way how to export all data of the project isn't working as well as it is supposed to.

I have asked architects to export their Revit IFC model in such so we can see Parent objects and their Parts (Similar to how Tekla exports its IFC models natively) 
![image](https://user-images.githubusercontent.com/120371523/207048214-b5d41e6c-51b4-4e87-b677-12c6aa174aad.png)
![image](https://user-images.githubusercontent.com/120371523/207048271-13335241-9e93-4fd9-b0fd-1092b7582c55.png)

Configuration:
1. Create parts from Walls, Floors, Roofs,Facade
![image](https://user-images.githubusercontent.com/120371523/207047604-73b08d05-dd0b-4ffb-9c4e-d4e7e474c23e.png)
2. Make sure that you are using 3D View and in the view properties - Parts Visibility: Show parts 
![image](https://user-images.githubusercontent.com/120371523/207048490-d228e44f-d485-4744-bd30-223650ac7bce.png)
3. Export with configuration: Export only elements visible in view
![image](https://user-images.githubusercontent.com/120371523/207048718-610cc106-a5b8-440c-badd-aad9dc293ab5.png)

In the result I got this:
![image](https://user-images.githubusercontent.com/120371523/207048827-d6ea23c0-a268-439f-a9ee-a2f9199296df.png)

Model prefab walls were created as "Structural Columns"

I have attempted to:
Export via standard Revit 2020 IFC Exporter
Export via the latest Revit 2020 IFC Exporter
Upgrade and Export via standard Revit 2021 IFC Exporter
Upgrade and Export via the latest Revit 2021 IFC Exporter
Change IFC Options (Changing Structural columns to IFCStandartWallCase, etc.) 

None of these attempts have solved the issue. 
I have narrowed the issue that Prefab families, Structural Columns, Standard Columns do not rotate accordingly when exporting mentioned configuration (I have used standard Revit tools/families)

Revit View:
![image](https://user-images.githubusercontent.com/120371523/207052407-716d0376-bf57-4ded-b568-b2ce7638d8e8.png)

IFC viewer view (BIM Vision):
![image](https://user-images.githubusercontent.com/120371523/207052703-0d9e9eaf-6742-48e9-81ce-5b149e9b812a.png)

If anyone has any recommendations on how to overcome this situation, that would be nice.

I'm including Revit 2021 file and IFC model
[Lab.zip](https://github.com/Autodesk/revit-ifc/files/10208252/Lab.zip)

**Comment by ERBRZ** [comment] 2023-01-05 14:11
Can I have any feedback from the development team?

Is it a bug or a feature?

**Comment by JOuellette-Autodesk** [comment] 2023-01-05 14:21
Hi @ERBRZ,
Thank you for the files. Have you tested with Revit 2023?

**Comment by ERBRZ** [comment] 2023-01-05 14:59
Hi, 
Thank you for your quick reply. 
I have no Revit 2023, only tested on 2020 and 2021 (also baseline and updated IFC exporters).

If you need that Revit 2021 file - im adding it here 
[Lab RVT file.zip](https://github.com/Autodesk/revit-ifc/files/10353133/Lab.RVT.file.zip)

**Comment by ERBRZ** [comment] 2023-01-05 15:00
.

**Comment by louistrue** [comment] 2023-01-05 15:14
@ERBRZ should this really be closed?

**Comment by JOuellette-Autodesk** [comment] 2023-01-05 15:17
I've reopened this for now, until we can determine where the issue is (Revit or open source I/O code) and when (version) it has been fixed. It may be that this is already fixed in later Revit and the open source IFC I/O code, but we want to make sure.

**Comment by JOuellette-Autodesk** [comment] 2023-02-15 06:37
This is working correctly in Revit 2023. @parrela can you see if this is working in 2022?

**Closed by JOuellette-Autodesk** 2023-02-15 06:37 UTC
Labels: problem, export, geometry, 2020, 2021, Triage, Revit

**Comment by ERBRZ** [comment] 2023-03-15 07:50
@JOuellette-Autodesk Hi, I just reviewed the status of this issue in the Revit 2023 (I have tried Standart IFC exporter and the Latest IFC Exporter version) and it is not working correctly as you said before. Look at the picture below:
Revit (Lab file)
![image](https://user-images.githubusercontent.com/120371523/225240592-4d02f1ff-dd40-4a01-9ab8-7eb0f85da9c0.png)
Exported IFC (Lab file)
![image](https://user-images.githubusercontent.com/120371523/225240831-471cf249-6feb-4a7a-9180-fa4d4183c6f4.png)
The situation got even worse - missing columns, walls and so.
**Please reopen this issue.**

Files (.rvt 2023 + .ifc 2023)
[Lab 2023.zip](https://github.com/Autodesk/revit-ifc/files/10977190/Lab.2023.zip)

**Comment by JOuellette-Autodesk** [comment] 2023-03-16 19:49
@ERBRZ We have tested your file on our end using Revit 23.0.1.318 and the IFC for Revit Addon 23.2.5.0
I have viewed it using the ACCA usBIM viewer. Everything looks good from our side. I have included my version of the IFC export, using the IFC4 Reference View [Architecture] setup. What export setup are you using?
[Lab-Validation.zip](https://github.com/Autodesk/revit-ifc/files/10995274/Lab-Validation.zip)

<img width="1920" alt="Revit 2023-IFC result 01" src="https://user-images.githubusercontent.com/92317495/225736222-0a61681e-0ae5-4478-a55f-6e3f9ca76171.png">

<img width="1920" alt="Revit 2023-IFC result 02" src="https://user-images.githubusercontent.com/92317495/225736243-1f1cf196-e530-4cb8-b2f6-72914a3248b3.png">

<img width="1920" alt="Revit 2023-IFC result 03" src="https://user-images.githubusercontent.com/92317495/225736252-a535bd52-8fbb-4da6-85e5-84e342990c36.png">

<img width="1920" alt="Revit 2023-IFC result 04" src="https://user-images.githubusercontent.com/92317495/225736265-3677892f-e7a1-4165-8179-bb2bbf397c5b.png">
