### ISSUE TITLE
In R23 the mapping for IfcProject does not seem to work

### ISSUE THREAD

**Issue by Teun1** [Autodesk/revit-ifc#602] opened 2023-02-23 18:24 UTC
Revit 2023.1.1 and exporter 23.2.3.0
In Revit 2023 the custom mapping to IfcProject does not work anymore. Not sure why.
I liked the way I could distinquish between IfcProject, IfcSite and IfcBuilding.
Is there a reason why the mapping to IfcProject does not work in R23 anymore?
[230222_TAB_R23.zip](https://github.com/Autodesk/revit-ifc/files/10816918/230222_TAB_R23.zip)

**Comment by dvrvb** [comment] 2023-02-28 09:39
Hi Teun, I just want to confirm that I experience the same regression in Revit 2023.1.1 opposed to version 2022. With the latest (pre release) version of the R2023 exporter it seems not to be possible anymore to create a custom pset for IfcProject, for IFC2x3CV2.0 as well as for IFC4RV1.2.

**Comment by AngelVelezSosa** [comment] 2023-02-28 14:02
I am doing a significant rewrite of how properties get mapped to psets so I can take a look.  @dvrvb do you have a small sample that you can send me?

**Comment by dvrvb** [comment] 2023-03-01 04:22
Attached a little sample for a custom Pset "RBS" for IfcProject, IfcSite, IfcBuilding, IfcBuildingStorey. Only for IfcProject it seems to be missing.
[2023-03-01 R2023 IfcProject Custom Pset.zip](https://github.com/Autodesk/revit-ifc/files/10857094/2023-03-01.R2023.IfcProject.Custom.Pset.zip)

**Comment by dvrvb** [comment] 2023-06-02 07:41
Issue is fixed in version 23.3.0.0.
(tested for IFC2x3CV2.0 and IFC4RV1.2)

**Closed** 2023-06-02 12:28 UTC
Labels: problem, in progress, parameters-properties, 2023, Revit, IFC mapping
